# CI de Nível 01 - Execução Manual através de clique. Teste

stages:
  - test

#nome do job
e2e-tests:
  stage: test

  # maquina onde o job vai rodar
  image: node:24

  # disparo manual
  when: manual
git log --oneline -5
  script:
    # instalação do Yarn
    - npm install -g yarn

    # instalação das dependências
    - yarn

    # instalação dos browsers do Playwright + dependências
    - npx playwright install --with-deps

    # executar os testes e2e
    - yarn run e2e

  # salvar relatório 
  artifacts:
    when: always
    paths:
      - playwright-report/
    expire_in: 7 days